language: c

python:
    - "2.7"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y git make gcc g++ python3-ply ncurses-dev python-yaml
    - wget https://nexus.zephyrproject.org/content/repositories/releases/org/zephyrproject/zephyr-sdk/0.9/zephyr-sdk-0.9-setup.run
    - chmod +x zephyr-sdk-0.9-setup.run
    - yes | sudo ./zephyr-sdk-0.9-setup.run

notifications:
      email: false
